name: Main
on:
  push:
    branches: master
  repository_dispatch:
    types: [deploy]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pause for 25 seconds
        run: |
          sleep 25
